// This file will be auto-generated by the Supabase CLI.
// It will contain the TypeScript types for your database schema.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      episodes: {
        Row: {
          id: string
          title: string
          summary: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          summary?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          summary?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      paragraphs: {
        Row: {
          id: string
          episode_id: string
          content: string | null
          order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          episode_id: string
          content?: string | null
          order: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          episode_id?: string
          content?: string | null
          order?: number
          created_at?: string
          updated_at?: string
        }
      }
      reference_cards: {
        Row: {
          id: string
          title: string
          summary: string
          is_pinned: boolean | null
          group: string | null
          is_in_hold: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          summary: string
          is_pinned?: boolean | null
          group?: string | null
          is_in_hold?: boolean | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          summary?: string
          is_pinned?: boolean | null
          group?: string | null
          is_in_hold?: boolean | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
  }
}
