import { createClient } from '@supabase/supabase-js'

// Note: The `Database` type will be generated by the Supabase CLI.
// We are creating a placeholder file `types/supabase.ts` for it.
import { Database } from '@/types/supabase'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase URL or Anon Key in environment variables.')
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey)
